apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iqrwds7ap-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:bf5f71cf7ba6b323c704f0df802bbaa87dd328a8@sha256:f4336fa7e1a6c2cf7d1de1397c07f3ce01bb21bd61ce7a5f6ff47894492f5fc8
          name: container-image
